// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {FinancingController} from "../../src/FinancingController.sol";
import {Groth16Verifier} from "../../generated/Groth16Verifier.sol";
import {IEvidenceRegistry} from "../../src/interfaces/IEvidenceRegistry.sol";
import {IFinancingController} from "../../src/interfaces/IFinancingController.sol";
import {ControllerBase} from "../core/ControllerBase.sol";

/// @notice A real Groth16 proof, generated by circuits/ from the Go backend's epoch, verified by the
///         real snarkjs-generated verifier inside the real FinancingController.
///
/// The proof is bound to addresses, so the verifier and controller are pinned to fixed addresses.
/// Regenerate the fixtures with `make zk-fixture` (it writes proof_inputs.json from chain state,
/// proves against them, then re-runs this suite).
contract RealProofTest is ControllerBase {
    address internal constant VERIFIER_ADDR = address(0x7e57000000000000000000000000000000000001);
    address internal constant CONTROLLER_ADDR = address(0x7e57000000000000000000000000000000000002);

    string internal constant EPOCH_FIXTURE = "../circuits/test/fixtures/epoch_fixture.json";
    string internal constant INPUTS = "test/fixtures/proof_inputs.json";
    string internal constant PROOF = "test/fixtures/real_proof.json";

    // Aggregates of the fixture's eight readings (circuits/test/fixtures/epoch_fixture.json): the mean
    // position, and the highest humidity (67.84%) and shock (0.25 g), all inside the base policy.
    int32 internal constant CENTROID_LAT = 18_940_782;
    int32 internal constant CENTROID_LON = 72_966_092;
    uint16 internal constant MAX_HUMIDITY = 6784;
    uint16 internal constant MAX_SHOCK = 25;

    uint256[2] internal a;
    uint256[2][2] internal b;
    uint256[2] internal c;

    function _deployController() internal override returns (FinancingController) {
        // Deploy normally, then move the runtime code (immutables are embedded in it) to fixed addresses
        // so the proof's context, which binds both addresses, is reproducible.
        Groth16Verifier realVerifier = new Groth16Verifier();
        vm.etch(VERIFIER_ADDR, address(realVerifier).code);

        FinancingController tmp = new FinancingController(
            address(access),
            address(registry),
            address(policies),
            address(evidence),
            address(vault),
            VERIFIER_ADDR,
            address(ebl)
        );
        vm.etch(CONTROLLER_ADDR, address(tmp).code);
        vm.store(CONTROLLER_ADDR, bytes32(0), vm.load(address(tmp), bytes32(0))); // reentrancy guard slot
        return FinancingController(CONTROLLER_ADDR);
    }

    /// Commits the Go backend's 8-reading recovery epoch (root from the shared fixture) after the pause.
    function _recoveryEpoch() internal returns (bytes32 epochId, bytes32 root) {
        root = vm.parseJsonBytes32(vm.readFile(EPOCH_FIXTURE), ".rootHex");
        vm.prank(worker);
        epochId = evidence.commitEpoch(
            id,
            2,
            2,
            root,
            uint64(block.timestamp - 600),
            uint64(block.timestamp - 60),
            89,
            400,
            1200,
            true,
            IEvidenceRegistry.EpochTelemetry({
                latE6: CENTROID_LAT,
                lonE6: CENTROID_LON,
                maxHumidityX100: MAX_HUMIDITY,
                maxShockX100: MAX_SHOCK
            })
        );
    }

    function _loadProof() internal {
        string memory p = vm.readFile(PROOF);
        a = [vm.parseJsonUint(p, ".a[0]"), vm.parseJsonUint(p, ".a[1]")];
        b = [
            [vm.parseJsonUint(p, ".b[0][0]"), vm.parseJsonUint(p, ".b[0][1]")],
            [vm.parseJsonUint(p, ".b[1][0]"), vm.parseJsonUint(p, ".b[1][1]")]
        ];
        c = [vm.parseJsonUint(p, ".c[0]"), vm.parseJsonUint(p, ".c[1]")];
    }

    /// Fails loudly if the contract's context no longer matches the one the proof was made for.
    function _requireFreshFixture(bytes32 epochId) internal view {
        string memory p = vm.readFile(PROOF);
        require(
            vm.parseJsonUint(p, ".contextHash") == controller.proofContext(id, epochId, exporter),
            "STALE_FIXTURE: run `make zk-fixture`"
        );
        require(
            vm.parseJsonUint(p, ".merkleRoot")
                == uint256(vm.parseJsonBytes32(vm.readFile(EPOCH_FIXTURE), ".rootHex")),
            "STALE_FIXTURE: epoch root changed; run `make zk-fixture`"
        );
    }

    /// Generator hook: writes the exact public inputs a proof must be made for. Only runs on request.
    function test_writeProofInputs() public {
        if (!vm.envOr("WRITE_PROOF_INPUTS", false)) vm.skip(true);
        _pausedAfterAnomaly();
        (bytes32 epochId, bytes32 root) = _recoveryEpoch();

        string memory o = "inputs";
        vm.serializeString(
            o, "contextHash", vm.toString(controller.proofContext(id, epochId, exporter))
        );
        vm.serializeString(o, "merkleRoot", vm.toString(uint256(root)));
        vm.serializeInt(o, "minTempX100", int256(policy.minTempX100));
        vm.serializeInt(o, "maxTempX100", int256(policy.maxTempX100));
        vm.serializeBytes32(o, "shipmentId", id);
        vm.serializeBytes32(o, "epochId", epochId);
        vm.serializeAddress(o, "submitter", exporter);
        vm.serializeAddress(o, "verifier", VERIFIER_ADDR);
        vm.serializeAddress(o, "controller", CONTROLLER_ADDR);
        vm.serializeUint(o, "chainId", block.chainid);
        string memory out = vm.serializeUint(o, "pauseCount", controller.getFacility(id).pauseCount);
        vm.writeJson(out, INPUTS);
    }

    function test_realProofResumesTheFacilityAndUnblocksM3() public {
        _pausedAfterAnomaly();
        (bytes32 epochId,) = _recoveryEpoch();
        _requireFreshFixture(epochId);
        _loadProof();

        uint256 gasBefore = gasleft();
        vm.prank(exporter);
        controller.resumeWithProof(id, 2, 2, a, b, c);
        emit log_named_uint(
            "resumeWithProof gas (real Groth16 verification)", gasBefore - gasleft()
        );

        assertEq(
            uint8(controller.getFacility(id).status), uint8(IFinancingController.Status.ACTIVE)
        );
        assertTrue(evidence.getEpoch(epochId).proofVerified);

        vm.prank(exporter);
        controller.evaluateAndReleaseMilestone(id, 2, 2);
        assertEq(
            usdg.balanceOf(exporter), 24_000e6, "delayed M3 tranche released after the real proof"
        );
    }

    function test_tamperedProofIsRejected() public {
        _pausedAfterAnomaly();
        (bytes32 epochId,) = _recoveryEpoch();
        _requireFreshFixture(epochId);
        _loadProof();
        a[0] += 1;
        vm.prank(exporter);
        vm.expectRevert(IFinancingController.InvalidProof.selector);
        controller.resumeWithProof(id, 2, 2, a, b, c);
        assertEq(
            uint8(controller.getFacility(id).status), uint8(IFinancingController.Status.PAUSED)
        );
    }

    function test_proofCannotBeReplayedBySomeoneElse() public {
        _pausedAfterAnomaly();
        (bytes32 epochId,) = _recoveryEpoch();
        _requireFreshFixture(epochId);
        _loadProof();
        // an operator relayer holding the proof cannot submit it: the context binds the exporter
        vm.prank(manager);
        vm.expectRevert(IFinancingController.InvalidProof.selector);
        controller.resumeWithProof(id, 2, 2, a, b, c);
    }

    function test_proofDoesNotTransferToADifferentCommittedEpoch() public {
        _pausedAfterAnomaly();
        (bytes32 epochId,) = _recoveryEpoch();
        _requireFreshFixture(epochId);
        _loadProof();
        // a different epoch (other root, other sequence) for the same milestone
        vm.prank(worker);
        evidence.commitEpoch(
            id,
            2,
            3,
            bytes32(uint256(12345)),
            uint64(block.timestamp - 600),
            uint64(block.timestamp - 60),
            89,
            400,
            1200,
            true,
            IEvidenceRegistry.EpochTelemetry({
                latE6: CENTROID_LAT,
                lonE6: CENTROID_LON,
                maxHumidityX100: MAX_HUMIDITY,
                maxShockX100: MAX_SHOCK
            })
        );
        vm.prank(exporter);
        vm.expectRevert(IFinancingController.InvalidProof.selector);
        controller.resumeWithProof(id, 2, 3, a, b, c);
    }

    function test_realProofCannotBeReusedOnceConsumed() public {
        _pausedAfterAnomaly();
        (bytes32 epochId,) = _recoveryEpoch();
        _requireFreshFixture(epochId);
        _loadProof();
        vm.prank(exporter);
        controller.resumeWithProof(id, 2, 2, a, b, c);
        vm.prank(exporter);
        vm.expectRevert(
            abi.encodeWithSelector(
                IFinancingController.InvalidState.selector, IFinancingController.Status.ACTIVE
            )
        );
        controller.resumeWithProof(id, 2, 2, a, b, c);
    }
}
