// Regenerates src/lib/chain/abis.ts from the Foundry build output so the frontend's ABIs never drift from the
// contracts. Run `forge build` in contracts/ first, then `pnpm abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const out = fileURLToPath(new URL("../../contracts/out/", import.meta.url));
const targets = {
  controllerAbi: "FinancingController",
  registryAbi: "ShipmentRegistry",
  policiesAbi: "PolicyEngine",
  vaultAbi: "ReceivableVault",
  evidenceAbi: "EvidenceRegistry",
  accessAbi: "CargoFlowAccess", // hasRole: who may arbitrate disputes
  usdgAbi: "MockUSDG", // the ERC-20 surface (approve, allowance, balanceOf) plus mint on local chains
};

let src = "// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.\n\n";
for (const [name, contract] of Object.entries(targets)) {
  const json = JSON.parse(readFileSync(`${out}${contract}.sol/${contract}.json`, "utf8"));
  src += `export const ${name} = ${JSON.stringify(json.abi, null, 2)} as const;\n\n`;
}
writeFileSync(fileURLToPath(new URL("../src/lib/chain/abis.ts", import.meta.url)), src);
console.log(`wrote ${Object.keys(targets).length} ABIs`);
