// Regenerates src/contracts/abis/<version>.ts from the Foundry build output (contracts/out), so the SDK's ABIs never
// drift from the contracts. Run `forge build` in contracts/ first, then `pnpm abi` (or `pnpm abi v3` for a new set).
//
// Each contract version gets its own file. v2 signatures are frozen (do not regenerate v2 from a v3 build); v3 adds
// cancelFacility, bindTitle, parametric cover, Pausable, and the DeviceRegistry and EBLRegistry contracts.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const TARGETS = {
  v2: {
    financingControllerAbi: "FinancingController",
    shipmentRegistryAbi: "ShipmentRegistry",
    policyEngineAbi: "PolicyEngine",
    evidenceRegistryAbi: "EvidenceRegistry",
    receivableVaultAbi: "ReceivableVault",
    coverPoolAbi: "CoverPool",
    accessAbi: "CargoFlowAccess",
    usdgAbi: "MockUSDG", // the ERC-20 surface (approve, allowance, balanceOf) plus mint on test deployments
  },
  v3: {
    financingControllerAbi: "FinancingController",
    shipmentRegistryAbi: "ShipmentRegistry",
    policyEngineAbi: "PolicyEngine",
    evidenceRegistryAbi: "EvidenceRegistry",
    receivableVaultAbi: "ReceivableVault",
    coverPoolAbi: "CoverPool",
    accessAbi: "CargoFlowAccess",
    usdgAbi: "MockUSDG",
    deviceRegistryAbi: "DeviceRegistry",
    eblRegistryAbi: "EBLRegistry",
  },
};

const version = process.argv[2] ?? "v2";
const targets = TARGETS[version];
if (!targets || Object.keys(targets).length === 0) {
  console.error(`no ABI targets for ${version}; add them to TARGETS in scripts/gen-abis.mjs`);
  process.exit(1);
}
const out = fileURLToPath(new URL("../../../contracts/out/", import.meta.url));
let src = `// Generated by scripts/gen-abis.mjs from contracts/out (contracts ${version}). Do not edit by hand.\n\n`;
for (const [name, contract] of Object.entries(targets)) {
  const file = `${out}${contract}.sol/${contract}.json`;
  if (!existsSync(file)) {
    console.error(`missing ${file}; run forge build in contracts/`);
    process.exit(1);
  }
  const json = JSON.parse(readFileSync(file, "utf8"));
  src += `export const ${name} = ${JSON.stringify(json.abi, null, 2)} as const;\n\n`;
}
writeFileSync(fileURLToPath(new URL(`../src/contracts/abis/${version}.ts`, import.meta.url)), src);
console.log(`wrote ${Object.keys(targets).length} ${version} ABIs`);
