// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.

export const controllerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "access",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "registry",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "policies",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "evidence",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "vault",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "verifier",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ACCESS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAccessControl"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EVIDENCE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IEvidenceRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_MILESTONES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "POLICIES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPolicyEngine"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IShipmentRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "VAULT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IReceivableVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "VERIFIER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IGroth16Verifier"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createFacility",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "financier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "milestones",
        "type": "tuple[]",
        "internalType": "struct IFinancingController.MilestoneSpec[]",
        "components": [
          {
            "name": "allocation",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "evidenceThreshold",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "checkpointCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depositCapital",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "evaluateAndReleaseMilestone",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "milestoneIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getFacility",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IFinancingController.FacilityState",
        "components": [
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum IFinancingController.Status"
          },
          {
            "name": "exporter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "financier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "buyer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "committed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "milestoneCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nextMilestone",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "pauseReason",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "pausedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "pauseCount",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMilestone",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "index",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IFinancingController.MilestoneSpec",
        "components": [
          {
            "name": "allocation",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "evidenceThreshold",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "checkpointCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markDefaulted",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "ref",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "markDelivered",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openDispute",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "reason",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pauseFinancing",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "reasonCode",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "proofContext",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "epochId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolveDispute",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "resume",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "resolutionRef",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resumeByVerifier",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "basis",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resumeWithProof",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "milestoneIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "a",
        "type": "uint256[2]",
        "internalType": "uint256[2]"
      },
      {
        "name": "b",
        "type": "uint256[2][2]",
        "internalType": "uint256[2][2]"
      },
      {
        "name": "c",
        "type": "uint256[2]",
        "internalType": "uint256[2]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settle",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "startTransit",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "DefaultDeclared",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "declaredBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "ref",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeliveryConfirmed",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "confirmedBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeOpened",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "openedBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeResolved",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "resolvedBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "resumed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "resolutionRef",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilityCreated",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "financier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "exporter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "committed",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "feeBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "milestoneCount",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FinancingPaused",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reasonCode",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "pausedBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FinancingResumed",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "resumedBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "basis",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MilestoneAdvanceReleased",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "milestoneIndex",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "epochId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "totalDrawn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StatusChanged",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "from",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum IFinancingController.Status"
      },
      {
        "name": "to",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum IFinancingController.Status"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EvidenceBelowThreshold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EvidenceConflictTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EvidenceNotCompliant",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EvidenceRiskTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EvidenceStale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityAlreadyCreated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidCounterparty",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMilestones",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidProofContext",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidReason",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidState",
    "inputs": [
      {
        "name": "current",
        "type": "uint8",
        "internalType": "enum IFinancingController.Status"
      }
    ]
  },
  {
    "type": "error",
    "name": "MilestoneAlreadyReleased",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MilestoneOutOfOrder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MilestonesIncomplete",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAuthorizedForShipment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAuthorizedToPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBuyer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotExporter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFinancier",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProofRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StaleRecoveryEvidence",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;

export const registryAbi = [
  {
    "type": "function",
    "name": "getShipment",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "s",
        "type": "tuple",
        "internalType": "struct IShipmentRegistry.Shipment",
        "components": [
          {
            "name": "exporter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "buyer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "invoiceHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "routeCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "policyCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "invoiceValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "exists",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerShipment",
    "inputs": [
      {
        "name": "externalRef",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "buyer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "invoiceHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "routeCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "invoiceValue",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "shipmentIdFor",
    "inputs": [
      {
        "name": "exporter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "externalRef",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "event",
    "name": "ShipmentRegistered",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "exporter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "invoiceHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "routeCommitment",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "invoiceValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidCommitment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidCounterparty",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInvoiceValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ShipmentAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ShipmentNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;

export const policiesAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IShipmentRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPolicy",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IPolicyEngine.Policy",
        "components": [
          {
            "name": "minTempX100",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "maxTempX100",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "maxEvidenceAgeSec",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxRouteDeviationM",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minEvidenceScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxConflictBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxRiskBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "requiresZK",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashPolicy",
    "inputs": [
      {
        "name": "policy",
        "type": "tuple",
        "internalType": "struct IPolicyEngine.Policy",
        "components": [
          {
            "name": "minTempX100",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "maxTempX100",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "maxEvidenceAgeSec",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxRouteDeviationM",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minEvidenceScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxConflictBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxRiskBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "requiresZK",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "isSet",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setPolicy",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "policy",
        "type": "tuple",
        "internalType": "struct IPolicyEngine.Policy",
        "components": [
          {
            "name": "minTempX100",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "maxTempX100",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "maxEvidenceAgeSec",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxRouteDeviationM",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "minEvidenceScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxConflictBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxRiskBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "requiresZK",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "PolicySet",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidPolicy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotExporter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PolicyAlreadySet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PolicyCommitmentMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PolicyNotSet",
    "inputs": []
  }
] as const;

export const vaultAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "access",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "usdg",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ACCESS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAccessControl"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "USDG",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closeDefaulted",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getFacility",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IReceivableVault.Facility",
        "components": [
          {
            "name": "financier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "supplier",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "committed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "drawn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "invoiceValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "funded",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "paused",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "closed",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openFacility",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "financier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "supplier",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "payer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "committed",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "invoiceValue",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "feeBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "release",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPaused",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "paused",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settle",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AdvanceReleased",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "supplier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "totalDrawn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CapitalDeposited",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "financier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilityDefaulted",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "undrawnRefund",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "outstandingPrincipal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilityOpened",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "financier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "supplier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "committed",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "invoiceValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "feeBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilityPauseSet",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "paused",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilitySettled",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "principal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "residual",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "undrawnRefund",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyFunded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExceedsCommittedFacility",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FacilityPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidFacility",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFunded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const;

export const evidenceAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "access",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ACCESS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAccessControl"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "commitEpoch",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "milestoneIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "merkleRoot",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "startTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "endTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "score",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "conflictBps",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "riskBps",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "compliant",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "epochId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "epochIdFor",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "milestoneIndex",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getEpoch",
    "inputs": [
      {
        "name": "epochId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "e",
        "type": "tuple",
        "internalType": "struct IEvidenceRegistry.EvidenceEpoch",
        "components": [
          {
            "name": "shipmentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "merkleRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "startTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "endTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "committedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "score",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "conflictBps",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "riskBps",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "milestoneIndex",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "compliant",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "proofVerified",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markProofVerified",
    "inputs": [
      {
        "name": "epochId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "EvidenceEpochCommitted",
    "inputs": [
      {
        "name": "shipmentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "epochId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "milestoneIndex",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "merkleRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "score",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "conflictBps",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "riskBps",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "compliant",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EvidenceProofVerified",
    "inputs": [
      {
        "name": "epochId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EpochAlreadyCommitted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EpochNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidEpoch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProofAlreadyVerified",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;

export const usdgAbi = [
  {
    "type": "function",
    "name": "allowance",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "approve",
    "inputs": [
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "balanceOf",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "decimals",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "mint",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "symbol",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalSupply",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transfer",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Approval",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "spender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Transfer",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ERC20InsufficientAllowance",
    "inputs": [
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allowance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InsufficientBalance",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidApprover",
    "inputs": [
      {
        "name": "approver",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidReceiver",
    "inputs": [
      {
        "name": "receiver",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidSender",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidSpender",
    "inputs": [
      {
        "name": "spender",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;

