// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {GeoDistance} from "../../src/libraries/GeoDistance.sol";

/// @notice GeoDistance against haversine reference values (float64, sphere of radius 6,371,008.8 m),
///         generated by test/libraries/geo_reference.py and embedded below. The tolerance applied is
///         exactly the accuracy bound stated in the library's NatSpec.
contract GeoDistanceTest is Test {
    struct Vector {
        int32 aLat;
        int32 aLon;
        int32 bLat;
        int32 bLon;
        uint256 refMm; // haversine distance in millimetres
    }

    Vector[] internal vectors;
    uint256 internal namedCount;

    function _v(int32 aLat, int32 aLon, int32 bLat, int32 bLon, uint256 refMm) internal {
        vectors.push(Vector({aLat: aLat, aLon: aLon, bLat: bLat, bLon: bLon, refMm: refMm}));
    }

    function setUp() public {
        _v(18950000, 72950000, 18950000, 72950000, 0); // zero distance (JNPT)
        _v(0, 0, 0, 1000000, 111195080); // equator, 1 deg of longitude
        _v(0, 30000000, 1000000, 30000000, 111195080); // meridian, 1 deg of latitude
        _v(-1000000, 30000000, 1000000, 31000000, 248637233); // equator crossing
        _v(0, 179500000, 0, -179500000, 111195080); // antimeridian on the equator
        _v(60000000, 179800000, 60000000, -179800000, 22238982); // antimeridian at 60N
        _v(52000000, 179000000, 53000000, -178000000, 231497332); // antimeridian, Bering Sea
        _v(-60000000, -179000000, -60500000, 179000000, 123560914); // antimeridian at 60S
        _v(59913900, 10752200, 59329300, 18068600, 416299099); // 60N Oslo-Stockholm
        _v(-60000000, 0, -60000000, 5000000, 277921537); // 60S, 5 deg of longitude
        _v(80000000, 0, 80000000, 10000000, 192850611); // 80N, 10 deg of longitude
        _v(80000000, 0, 79000000, 5000000, 150334545); // 80N to 79N diagonal
        _v(-70000000, -60000000, -71000000, -62000000, 133683399); // 70S Weddell
        _v(18950000, 72950000, 18940782, 72966092, 1978611); // JNPT berth to epoch centroid
        _v(1264000, 103840000, 1300000, 103800000, 5983080); // Singapore approach
        _v(10000000, 20000000, 10008993, 20000000, 999977); // 1 km due north
        _v(0, 0, 0, 8993216, 1000001375); // 1,000 km along the equator
        namedCount = vectors.length;
        _v(-60940818, 905672, -59423871, -2588268, 256399509);
        _v(-63578104, -99617560, -68572032, -104768117, 601429597);
        _v(45339741, 17212124, 45618183, 12539901, 365538963);
        _v(40164153, 31147505, 38518909, 29328431, 240694111);
        _v(-62282153, 114034087, -61424098, 110140458, 225377743);
        _v(29628491, 64580019, 29592587, 66762416, 211014506);
        _v(2174007, -152524836, 736405, -153067509, 170856880);
        _v(-33260500, -15318793, -35167509, -24573087, 876598328);
        _v(12387737, -171093851, 10283714, -168635951, 355720267);
        _v(-12445201, -36441602, -17716152, -36387964, 586132087);
        _v(-61368329, 2289150, -64027298, -2249683, 375323305);
        _v(-1435086, 150031669, -3478600, 151157728, 259384859);
        _v(68197299, -7491612, 70497869, -6382077, 259475636);
        _v(-44076021, -133560413, -44200412, -134160424, 49838814);
        _v(61891945, -143072503, 59135674, -142050873, 311532557);
        _v(-2861902, -97586183, -8413397, -103332478, 886035303);
        _v(-6912585, -11013827, -2745881, -11349064, 464802875);
        _v(7301163, 21526579, 5134642, 27183515, 670084183);
        _v(47968320, 683861, 49561489, -1525040, 239967586);
        _v(-10709307, -74025308, -8335165, -73519037, 269766858);
        _v(24902834, 35018358, 22858476, 34697195, 229655564);
        _v(-1677196, 151743500, -4013423, 151956377, 260850368);
        _v(1802685, 117422464, -1594899, 116130692, 404171670);
        _v(65162596, 119305052, 67592977, 115566375, 317340407);
        _v(-64260162, 68159927, -67773894, 67271565, 392756931);
        _v(-7532687, 167496553, -2711696, 160224226, 967300454);
        _v(-3336600, -156853744, -4541330, -156841753, 133966653);
        _v(-64533993, 89118476, -68024099, 92212498, 411899476);
        _v(-77754793, -179922971, -75334678, 175805561, 290739331);
        _v(-66709509, 105757418, -68277126, 101590301, 248589828);
        _v(40296801, 164292081, 38276523, 161410676, 334570072);
        _v(-55238255, -67160616, -54262866, -76101047, 583482360);
        _v(71989690, -2883990, 73956886, 5939662, 360515858);
        _v(-44331573, 31656426, -37926640, 23985034, 958319181);
        _v(755422, -149604045, 3517190, -150799965, 334608925);
        _v(45350073, 149405811, 42984954, 151384790, 306698298);
        _v(49279199, 7211132, 50167314, 7334572, 99151841);
        _v(-63018569, 139597473, -63285400, 140455708, 52324040);
        _v(-23455551, 97032146, -23580015, 97023269, 13869348);
        _v(-27558391, -70678180, -25415968, -68431333, 326716644);
        _v(71805146, 25782559, 73597584, 36391969, 402664369);
        _v(3138197, -23901276, 664838, -25655145, 337082441);
        _v(28559729, -154976949, 29150459, -153035269, 200179323);
        _v(67432872, -163714827, 69627561, -175728572, 545221703);
        _v(-7708663, 91695490, -7915558, 90858088, 95076070);
        _v(60450704, -133509680, 61159708, -143189588, 530406590);
        _v(2696426, 164371485, 3103523, 163766251, 81034974);
        _v(-17604570, -26872461, -14313587, -25047797, 414672660);
    }

    // ------------------------------------------------------------------ helpers

    /// The bound stated in GeoDistance's NatSpec, in parts per million of the reference distance.
    function _tolPpm(uint256 maxAbsLatE6, uint256 refMm) internal pure returns (uint256) {
        bool upTo500Km = refMm <= 500_000_000;
        if (maxAbsLatE6 <= 60_000_000) return upTo500Km ? 1_000 : 3_000;
        if (maxAbsLatE6 <= 70_000_000) return upTo500Km ? 2_000 : 7_500;
        return upTo500Km ? 8_000 : 32_000;
    }

    function _abs(int256 x) internal pure returns (uint256) {
        return uint256(x < 0 ? -x : x);
    }

    function _max(uint256 a, uint256 b) internal pure returns (uint256) {
        return a > b ? a : b;
    }

    /// |d - ref| <= tol * ref + 1 m (integer rounding to whole metres)
    function _assertWithinBound(Vector memory v, uint256 dM, string memory label) internal pure {
        uint256 dMm = dM * 1000;
        uint256 diff = dMm > v.refMm ? dMm - v.refMm : v.refMm - dMm;
        uint256 maxLat = _max(_abs(v.aLat), _abs(v.bLat));
        uint256 allowed = (v.refMm * _tolPpm(maxLat, v.refMm)) / 1_000_000 + 1000;
        assertLe(diff, allowed, label);
    }

    /// Wraps a longitude into [-180e6, 180e6).
    function _wrapLon(int256 lon) internal pure returns (int32) {
        int256 span = 360_000_000;
        int256 v = ((lon + 180_000_000) % span + span) % span - 180_000_000;
        // forge-lint: disable-next-line(unsafe-typecast)
        return int32(v); // in [-180e6, 180e6): fits int32
    }

    function _d(Vector memory v) internal pure returns (uint256) {
        return GeoDistance.distanceM(v.aLat, v.aLon, v.bLat, v.bLon);
    }

    // ------------------------------------------------------------------ reference vectors

    function test_namedVectorsMatchHaversineWithinTheStatedBound() public view {
        for (uint256 i; i < namedCount; ++i) {
            _assertWithinBound(vectors[i], _d(vectors[i]), vm.toString(i));
        }
    }

    function test_randomVectorsMatchHaversineWithinTheStatedBound() public view {
        assertEq(vectors.length - namedCount, 48);
        for (uint256 i = namedCount; i < vectors.length; ++i) {
            _assertWithinBound(vectors[i], _d(vectors[i]), vm.toString(i));
        }
    }

    /// Rotating both longitudes, mirroring across the equator and swapping the endpoints leave the
    /// haversine distance unchanged, so every reference vector yields many more, including ones that
    /// straddle the antimeridian at every latitude band.
    function testFuzz_referenceVectorsUnderRotationReflectionAndSwap(
        uint256 index,
        int256 shift,
        bool mirror,
        bool swap
    ) public view {
        Vector memory v = vectors[bound(index, 0, vectors.length - 1)];
        shift = bound(shift, -360_000_000, 360_000_000);
        v.aLon = _wrapLon(int256(v.aLon) + shift);
        v.bLon = _wrapLon(int256(v.bLon) + shift);
        if (mirror) (v.aLat, v.bLat) = (-v.aLat, -v.bLat);
        if (swap) (v.aLat, v.aLon, v.bLat, v.bLon) = (v.bLat, v.bLon, v.aLat, v.aLon);
        _assertWithinBound(v, _d(v), "transformed reference vector");
    }

    // ------------------------------------------------------------------ exact cases

    function test_zeroDistance() public pure {
        assertEq(GeoDistance.distanceM(18_950_000, 72_950_000, 18_950_000, 72_950_000), 0);
        assertEq(GeoDistance.distanceM(-90_000_000, 0, -90_000_000, 0), 0);
    }

    function test_oneDegreeOnTheEquatorAndOnAMeridian() public pure {
        assertEq(GeoDistance.distanceM(0, 0, 0, 1_000_000), 111_195);
        assertEq(GeoDistance.distanceM(0, 30_000_000, 1_000_000, 30_000_000), 111_195);
        assertEq(GeoDistance.distanceM(80_000_000, 5_000_000, 81_000_000, 5_000_000), 111_195);
    }

    function test_antimeridianCrossingTakesTheShortWay() public pure {
        uint256 across = GeoDistance.distanceM(0, 179_500_000, 0, -179_500_000);
        assertEq(across, GeoDistance.distanceM(0, -500_000, 0, 500_000));
        assertEq(across, 111_195);
        assertEq(
            GeoDistance.distanceM(60_000_000, 180_000_000, 60_000_000, -180_000_000),
            0,
            "+180 and -180 are the same meridian"
        );
    }

    function test_longitudeVanishesAtThePole() public pure {
        assertEq(GeoDistance.distanceM(90_000_000, 0, 90_000_000, 180_000_000), 0);
        assertEq(GeoDistance.distanceM(90_000_000, 0, 89_000_000, 0), 111_195);
    }

    function test_radiusBoundaryIsInclusive() public pure {
        // JNPT berth to the real-proof epoch's centroid: 1,978 m
        uint256 d = GeoDistance.distanceM(18_950_000, 72_950_000, 18_940_782, 72_966_092);
        assertEq(d, 1978);
        assertTrue(GeoDistance.withinRadius(18_950_000, 72_950_000, 18_940_782, 72_966_092, 1978));
        assertFalse(GeoDistance.withinRadius(18_950_000, 72_950_000, 18_940_782, 72_966_092, 1977));
        // the largest allowed radius
        assertTrue(GeoDistance.withinRadius(0, 0, 0, 8_993_200, 1_000_000));
        assertFalse(GeoDistance.withinRadius(0, 0, 0, 8_993_300, 1_000_000));
        // the smallest allowed radius
        assertTrue(GeoDistance.withinRadius(10_000_000, 20_000_000, 10_008_993, 20_000_000, 1000));
        assertFalse(GeoDistance.withinRadius(10_000_000, 20_000_000, 10_009_100, 20_000_000, 1000));
    }

    function test_cosineTableEndpointsAndInterpolation() public pure {
        assertEq(GeoDistance.cosE9(0), 1e9);
        assertEq(GeoDistance.cosE9(60_000_000), 500_000_000);
        assertEq(GeoDistance.cosE9(90_000_000), 0);
        assertEq(GeoDistance.cosE9(95_000_000), 0);
        // cos(45.5 deg) = 0.700909264; linear interpolation is within 4e-5 of it
        assertApproxEqAbs(GeoDistance.cosE9(45_500_000), 700_909_264, 40_000);
    }

    function test_coordinateValidation() public pure {
        assertTrue(GeoDistance.isValidCoordinate(90_000_000, 180_000_000));
        assertTrue(GeoDistance.isValidCoordinate(-90_000_000, -180_000_000));
        assertFalse(GeoDistance.isValidCoordinate(90_000_001, 0));
        assertFalse(GeoDistance.isValidCoordinate(-90_000_001, 0));
        assertFalse(GeoDistance.isValidCoordinate(0, 180_000_001));
        assertFalse(GeoDistance.isValidCoordinate(0, -180_000_001));
    }

    // ------------------------------------------------------------------ properties

    function _coord(int256 lat, int256 lon) internal pure returns (int32, int32) {
        // forge-lint: disable-next-line(unsafe-typecast)
        return
            (
                int32(bound(lat, -90_000_000, 90_000_000)),
                int32(bound(lon, -180_000_000, 180_000_000))
            );
    }

    function testFuzz_symmetric(int256 aLat, int256 aLon, int256 bLat, int256 bLon) public pure {
        (int32 la, int32 oa) = _coord(aLat, aLon);
        (int32 lb, int32 ob) = _coord(bLat, bLon);
        assertEq(GeoDistance.distanceM(la, oa, lb, ob), GeoDistance.distanceM(lb, ob, la, oa));
    }

    function testFuzz_samePointIsZero(int256 lat, int256 lon) public pure {
        (int32 la, int32 lo) = _coord(lat, lon);
        assertEq(GeoDistance.distanceM(la, lo, la, lo), 0);
        assertTrue(GeoDistance.withinRadius(la, lo, la, lo, 0));
    }

    /// Rotating both points about the polar axis never changes the result (antimeridian handling).
    function testFuzz_rotationInvariant(
        int256 aLat,
        int256 aLon,
        int256 bLat,
        int256 bLon,
        int256 shift
    ) public pure {
        (int32 la, int32 oa) = _coord(aLat, aLon);
        (int32 lb, int32 ob) = _coord(bLat, bLon);
        shift = bound(shift, -360_000_000, 360_000_000);
        assertEq(
            GeoDistance.distanceM(la, oa, lb, ob),
            GeoDistance.distanceM(la, _wrapLon(oa + shift), lb, _wrapLon(ob + shift))
        );
    }

    /// Along a meridian the haversine is the exact arc R * dLat, which can be computed here.
    function testFuzz_meridianMatchesTheExactArc(int256 aLat, int256 bLat, int256 lon) public pure {
        (int32 la, int32 lo) = _coord(aLat, lon);
        (int32 lb,) = _coord(bLat, 0);
        uint256 arcMm = (_abs(int256(la) - lb) * 111_195_080_234) / 1e9;
        uint256 dMm = GeoDistance.distanceM(la, lo, lb, lo) * 1000;
        assertApproxEqAbs(dMm, arcMm, 1000);
    }

    /// Along the equator the haversine is the exact arc R * dLon (the short way round).
    function testFuzz_equatorMatchesTheExactArc(int256 aLon, int256 bLon) public pure {
        (, int32 oa) = _coord(0, aLon);
        (, int32 ob) = _coord(0, bLon);
        uint256 dLon = _abs(int256(oa) - ob);
        if (dLon > 180_000_000) dLon = 360_000_000 - dLon;
        uint256 arcMm = (dLon * 111_195_080_234) / 1e9;
        assertApproxEqAbs(GeoDistance.distanceM(0, oa, 0, ob) * 1000, arcMm, 1000);
    }

    function testFuzz_cosineIsMonotonicAndBounded(uint256 x, uint256 y) public pure {
        x = bound(x, 0, 90_000_000);
        y = bound(y, x, 90_000_000);
        assertGe(GeoDistance.cosE9(x), GeoDistance.cosE9(y));
        assertLe(GeoDistance.cosE9(x), 1e9);
    }

    function testFuzz_withinRadiusAgreesWithDistance(
        int256 aLat,
        int256 aLon,
        int256 bLat,
        int256 bLon,
        uint32 radiusM
    ) public pure {
        (int32 la, int32 oa) = _coord(aLat, aLon);
        (int32 lb, int32 ob) = _coord(bLat, bLon);
        assertEq(
            GeoDistance.withinRadius(la, oa, lb, ob, radiusM),
            GeoDistance.distanceM(la, oa, lb, ob) <= radiusM
        );
    }

    /// No input in range can overflow: the result never exceeds half the equator plus the meridian.
    function testFuzz_neverRevertsAndIsBounded(int256 aLat, int256 aLon, int256 bLat, int256 bLon)
        public
        pure
    {
        (int32 la, int32 oa) = _coord(aLat, aLon);
        (int32 lb, int32 ob) = _coord(bLat, bLon);
        assertLe(GeoDistance.distanceM(la, oa, lb, ob), 20_015_087 + 20_015_087);
    }
}
